---
title: "Code I may need for Data Ana"
author: "KD"
date: "2023-10-03"
output: html_document
---
```{r}
> ggplot(drago, aes(x = Year)) +
+     geom_bar(fill = "skyblue", color = "black") +
+     labs(title = "Number of Samples per Year", x = "Year", y = "Count") +
+     theme_minimal()
#graph showing the number of individuals per year
```

```{r}
> drago$Date <- as.Date(drago$Date)
> drago$Day <- day(drago$Date)
> drago$Month <- month(drago$Date, label = TRUE)
> drago$Year <- year(drago$Date)

#Separate date column into 3 separate columns
```

```{R}
num_individuals <- nrow(drago)
#self explanatory
```

```{r}

df$Column1 <- as.character(df$Column1)

# Convert a column to numeric
df$Column2 <- as.numeric(df$Column2)

# Convert a column to date
df$DateColumn <- as.Date(df$DateColumn, format = "YYYY-MM-DD")
```

```{}
surveys[surveys == ""] <- NA
#makes whatever in " " na, works on empty cells

weird cells?
missing_data_points<- read_csv("surveys.csv", na = c("Not Recorded", "NA"))

```

```{}
group_by(sex) %>%
+ summarise()
very very useful. use together
```

```{}
#bocas <- bocas %>% 
 # na.omit()
#bocas <- bocas %>%
 # filter(!is.na(t)) %>%
 # head()

#surveys[surveys == ""] <- NA

```

```{}
bocas %>%
+ group_by(tag) %>%
+ summarise(count = n()) 
```

```{r}
turtles_sampled<- bocas %>% 
+ count(tag)
```
```{r}
eom_point() + 
  labs(x = "Carapace length (mm)",
       y = "Body Depth (mm)",
       color = "Crab color") + 
  scale_color_manual(values = c("pink", "skyblue")) + # why not!
  geom_smooth(method = "lm") +
  annotate("text", x = 20, y = 30, label = "R^2 == 0.988", parse=T, size=5)
```
